---
- name: Working with vaults
  hosts: databases
  become: true

  tasks:
    - name: Load variable from encrypted file
      include_vars:
        file: vault/secret
    - name: Display the encrypted variable
      debug:
        msg: "{{ secret }}"
